version: '3'

services:
  web:
    image: shafinsaleem/pkgtracker-ds:admin-v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - admin-data:/data
    ports:
      - "8080:8080"
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 2
        window: 5s

volumes:
  data: