version: '3'

services:
  web:
    build: .
    volumes:
      - data:/data
    ports:
      - "8080:8080"
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1

volumes:
  data: