# Generated by Django 4.2.7 on 2024-03-14 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracking_id', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('SHIPPED', 'Shipped')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('action_performed', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='tracker_app.parcel')),
            ],
        ),
    ]
