# Generated by Django 4.2.7 on 2024-03-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='location',
        ),
        migrations.AddField(
            model_name='parcel',
            name='departure',
            field=models.CharField(default='Helsinki', max_length=100),
        ),
        migrations.AddField(
            model_name='parcel',
            name='destination',
            field=models.CharField(default='Estonia', max_length=100),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped')], max_length=20),
        ),
    ]
