version: '3.8'
services:
  app:
    container_name: user-auth-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    networks:
      - app-network
      
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: authDB
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
